name: 'HaxExtend'

on:
  push:
  schedule:
    # run every 3 days on UTC 0/1/2am (8/9/10am CN time)
     - cron: '0 0,1,2 */3 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: |
            ghcr.io/lyj0309/hax_extend:latest

      -
        name: "run"
        run: |
          docker images
          docker run -e USERNAME=${{ secrets.USERNAME }} \
          -e PASSWORD=${{ secrets.PASSWORD }} \
          -e TWOCAPTCHA_TOKEN=${{ secrets.TWOCAPTCHA_TOKEN }} \
          ghcr.io/lyj0309/hax_extend:latest
          

