name: 'pushDocker'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: swr.ap-southeast-3.myhuaweicloud.com
          username: ${{ secrets.HW_AK }}
          password: ${{ secrets.HW_SEC }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: swr.ap-southeast-3.myhuaweicloud.com/lyj/haxExtend:latest
